version: '3.9'

services:
    docker-mysql:
        container_name: mysqldb
        image: mysql:5.7
        environment:
            - MYSQL_DATABASE=test
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_ROOT=root
            - MYSQL_PASSWORD=root
        ports:
            - '3307:3306'
        volumes:
#          - "./database/config/mycustom.cnf:/etc/mysql/conf.d/custom.cnf"
          - teste3-volume-mysql:/var/lib/mysql
          - "./database/init/script-creates.sql:/docker-entrypoint-initdb.d/1.sql"
          - "./database/init/script-inserts.sql:/docker-entrypoint-initdb.d/2.sql"
        networks:
          - teste-bridge
        command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
        healthcheck:
          test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
          timeout: 20s
          retries: 10

    api:        
        container_name: spring-api
        image: spring-sql_api
        restart: always
        build: ./api/
        depends_on:
          docker-mysql:
            condition: service_healthy
        ports: 
            - '8888:8080'
        environment:
            SPRING_DATASOURCE_URL: "jdbc:mysql://docker-mysql:3306/test?autoReconnect=true&useSSL=false"
        networks:
          - teste-bridge

volumes:
  teste3-volume-mysql:

networks:
  teste-bridge:
    driver: bridge