version: '3.9'

services:
    mysqldb:
        container_name: mysqldb
        image: mysql
        # command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_DATABASE: test
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - teste3-volume-mysql:/var/lib/mysql
            - "./init/script-creates.sql:/docker-entrypoint-initdb.d/1.sql"
            - "./init/script-inserts.sql:/docker-entrypoint-initdb.d/2.sql"
        ports:
            - '3307:3306'
        networks:
          - teste-bridge
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
    api:        
        # container_name: spring-api
        image: spring-sql_api
        restart: always
        build: ./api/
        depends_on:
          mysqldb:
            condition: service_healthy
        ports: 
            - '8888:8888'
        environment:
#          MYSQL_HOST: mysqldb
          MYSQL_USER: root
          MYSQL_PASSWORD: root
          MYSQL_PORT: 3306
        networks:
          - teste-bridge

volumes:
  teste3-volume-mysql:

networks:
  teste-bridge:
    driver: bridge